package com.example.honeypot_platform.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * A security alert generated by the detection engine from suspicious activity.
 * An alert may reference a single event, a whole session, or both.
 */
@Entity
@Table(name = "alerts", indexes = {
        @Index(name = "idx_alert_severity", columnList = "severity"),
        @Index(name = "idx_alert_created", columnList = "createdAt")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Alert {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "event_id")
    private AttackEvent event;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "session_id")
    private AttackSession session;

    /** Severity name (INFO/LOW/MEDIUM/HIGH/CRITICAL). */
    @Column(nullable = false, length = 20)
    private String severity;

    @Column(nullable = false, length = 255)
    private String message;

    /** NEW / ACKNOWLEDGED / RESOLVED. */
    @Column(nullable = false, length = 20)
    private String status;

    @Column(nullable = false)
    private LocalDateTime createdAt;

    @Column(length = 80)
    private String attackType;

    @Enumerated(EnumType.STRING)
    @Column(length = 20)
    private AttackStage stage;

    @Column(length = 45)
    private String sourceIp;

    /** Kill-chain narrative describing what the attacker did. */
    @Column(columnDefinition = "TEXT")
    private String description;

    @PrePersist
    void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
        if (status == null) {
            status = "NEW";
        }
        if (severity == null) {
            severity = Severity.MEDIUM.name();
        }
    }
}
