package com.example.honeypot_platform.dto;

import com.example.honeypot_platform.entity.Alert;

import java.time.LocalDateTime;

/** Flat view of a security alert generated by the detection engine. */
public record AlertResponse(
        Long id,
        String severity,
        String message,
        String status,
        LocalDateTime createdAt,
        String attackType,
        String stage,
        String sourceIp,
        String description,
        Long sessionId,
        Long eventId
) {
    public static AlertResponse from(Alert a) {
        return new AlertResponse(
                a.getId(), a.getSeverity(), a.getMessage(), a.getStatus(), a.getCreatedAt(),
                a.getAttackType(),
                a.getStage() != null ? a.getStage().name() : null,
                a.getSourceIp(), a.getDescription(),
                a.getSession() != null ? a.getSession().getId() : null,
                a.getEvent() != null ? a.getEvent().getId() : null);
    }
}
